---
name: Checks

on: [push]

jobs: 
  test-lint:
      name: Test and Lint
      # docker is preinstalled under ubuntu 20.04
      runs-on: ubuntu-20.04
      steps:
      # this step login to docker hub accpunt
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      # then we use checkout to access the code on the jobs
        - name: Checkout
          uses: actions/checkout@v2
      # then we run the tests one by one using docker-compose run
        - name: Test
          run: docker-compose run --rm app sh -c "python manage.py test"
        - name: Lint
          run: docker-compose run --rm app sh -c "flake8"


